# Generated by Django 3.1.14 on 2022-06-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oebl_irs_workflow', '0003_auto_20220628_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='LemmaArticle',
            fields=[
                ('issue_lemma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='oebl_irs_workflow.issuelemma')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserArticlePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_type', models.CharField(choices=[('VIEW', 'VIEW'), ('COMMENT', 'COMMENT'), ('ANNOTATE', 'ANNOTATE'), ('WRITE', 'WRITE')], max_length=8)),
                ('lemma_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oebl_editor.lemmaarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oebl_irs_workflow.irsuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserArticleAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_type', models.CharField(choices=[('VIEW', 'VIEW'), ('COMMENT', 'COMMENT'), ('ANNOTATE', 'ANNOTATE'), ('WRITE', 'WRITE')], max_length=8)),
                ('lemma_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oebl_editor.lemmaarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oebl_irs_workflow.irsuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LemmaArticleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_created=True, auto_now=True)),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('markup', models.JSONField()),
                ('lemma_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oebl_irs_workflow.issuelemma')),
            ],
        ),
        migrations.AddField(
            model_name='lemmaarticle',
            name='current_version',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='oebl_editor.lemmaarticleversion'),
        ),
    ]
