# Generated by Django 3.1.14 on 2022-06-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemmaarticleversion',
            name='lemma_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oebl_editor.lemmaarticle'),
        ),
    ]
