# Generated by Django 3.1.14 on 2022-07-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_editor', '0002_auto_20220630_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemmaarticleversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lemmaarticleversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
