# Generated by Django 3.1.14 on 2022-08-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_editor', '0004_auto_20220707_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lemmaarticle',
            name='current_version',
        ),
    ]
