# Generated by Django 3.1.13 on 2021-12-07 09:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import oebl_research_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_research_backend', '0004_auto_20210218_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='listentry',
            name='attachements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='', verbose_name=oebl_research_backend.models.get_attachements_path), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='listentry',
            name='references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='listentry',
            name='works',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth_modifier',
            field=models.CharField(blank=True, choices=[('ca.', 'ca.'), ('nach', 'nach'), ('vor', 'vor'), ('um', 'um')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_death_modifier',
            field=models.CharField(blank=True, choices=[('ca.', 'ca.'), ('nach', 'nach'), ('vor', 'vor'), ('um', 'um')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'männlich'), ('f', 'weiblich'), ('d', 'divers')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='religion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='title_of_nobility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listentry',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oebl_research_backend.list'),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oebl_research_backend.professiongroup'),
        ),
    ]
