# Generated by Django 3.1.13 on 2021-12-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_irs_workflow', '0001_initial'),
        ('oebl_research_backend', '0005_auto_20211207_1035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='IRSPerson',
        ),
    ]
