# Generated by Django 3.1.14 on 2022-02-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_research_backend', '0006_auto_20211209_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irsperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('männlich', 'männlich'), ('weiblich', 'weiblich'), ('divers', 'divers')], max_length=10, null=True),
        ),
    ]
