# Generated by Django 3.1.14 on 2022-02-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_research_backend', '0007_auto_20220218_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='irsperson',
            name='alternative_names',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
