# Generated by Django 3.1.14 on 2022-02-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_research_backend', '0008_irsperson_alternative_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='irsperson',
            name='secondary_literature',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
