# Generated by Django 3.1.14 on 2022-02-28 16:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_research_backend', '0009_irsperson_secondary_literature'),
    ]

    operations = [
        migrations.AddField(
            model_name='irsperson',
            name='zotero_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, null=True, size=None),
        ),
    ]
