# Generated by Django 3.1.14 on 2022-03-02 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_research_backend', '0010_irsperson_zotero_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irsperson',
            name='zotero_keys',
        ),
        migrations.AddField(
            model_name='irsperson',
            name='zotero_keys_about',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='irsperson',
            name='zotero_keys_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
    ]
