# Generated by Django 3.1.14 on 2022-03-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_research_backend', '0011_auto_20220302_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='irsperson',
            name='gideon_legacy_literature',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
