# Generated by Django 3.1.14 on 2022-03-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_research_backend', '0012_irsperson_gideon_legacy_literature'),
    ]

    operations = [
        migrations.AddField(
            model_name='irsperson',
            name='kinship',
            field=models.TextField(blank=True, null=True),
        ),
    ]
