# Generated by Django 3.1.14 on 2022-04-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_research_backend', '0013_irsperson_kinship'),
    ]

    operations = [
        migrations.AddField(
            model_name='irsperson',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
