# Generated by Django 3.1.14 on 2022-06-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_research_backend', '0014_irsperson_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irsperson',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='irsperson',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
