# Generated by Django 3.1.14 on 2022-06-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_irs_workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticlePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'VIEW'), ('COMMENT', 'COMMENT'), ('ANNOTATE', 'ANNOTATE'), ('WRITE', 'WRITE')], max_length=8)),
                ('lemma_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oebl_irs_workflow.issuelemma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oebl_irs_workflow.irsuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserArticleAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'VIEW'), ('COMMENT', 'COMMENT'), ('ANNOTATE', 'ANNOTATE'), ('WRITE', 'WRITE')], max_length=8)),
                ('lemma_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oebl_irs_workflow.issuelemma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oebl_irs_workflow.irsuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LemmaArticleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_created=True, auto_now=True)),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('markup', models.JSONField()),
                ('lemma_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oebl_irs_workflow.issuelemma')),
            ],
        ),
        migrations.CreateModel(
            name='LemmaArticle',
            fields=[
                ('issue_lemma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='oebl_irs_workflow.issuelemma')),
                ('published', models.BooleanField(default=False)),
                ('current_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oebl_irs_workflow.lemmaarticleversion')),
            ],
        ),
    ]
